### PR TITLE
fixed binary in .gitignore, remove binary, adjust config for dr3env (no TLS)

### PR DESCRIPTION
**Pull request by didacog**

### CODE REVIEW

**Review by proura — COMMENTED** [review]
Hi @didacog ! 

.drlm-core.toml are a optional config file, and you can run drlm-core without it. if this file not exists drlm-core uses the default values. You must also chage them. This values are in https://github.com/brainupdaters/drlm-core/blob/4435a1858f2c98ed35ed5c5fd57dabdfd5c55a25/lib/database.go#L21 and https://github.com/brainupdaters/drlm-core/blob/4435a1858f2c98ed35ed5c5fd57dabdfd5c55a25/lib/mino.go#L14.

**Comment by didacog** [comment]
@proura 
Ok, then will be better to rename it to .sample or .example? or maybe better .dr3env ?

The other changes are required to avoid pushing built binaries and ignoring them.

**Comment by didacog** [comment]
I'll update PR with the changes

**Comment by proura** [comment]
@didacog, nowadays I used this file for develop more confotable, but imho I think its important to have a config file were we can show some help about the parameter and other possible values accepted beyond the default. If you would have a specific dr3dev development environment config file, you can create and call it fom command line with --config=./paht/file.
`go run drlm-core.go --config="/path/to/config/.dr3dev".`

**Review by proura — APPROVED** [review]

**Pull request merged**
